### ISSUE TITLE
Distorted "Get Started" Button text in Github

### ISSUE THREAD

**Issue by TheGooner93** [liorgrossman/darkness#100]
* Site: github
* Theme: iceberg
* URL: https://github.com/liorgrossman/darkness/issues/new/choose
* Darkness Version: 2.0.0 Pro
* Browser: Chrome 70.0.3538.110
* Operating System: Mac OS X 10_14_1
* Resolution: 1680x1050
* Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Bug Description**
On trying to create a new issue in a Github repository, with the above configuration of Darkness, visited and active anchor elements button texts for the button "Get Started" appear in different shades. This makes it slightly unclear whether the button itself is clickable or not. In themes like Dusk, the button text the situation is worse, in that, the text is highly invisible. Please refer to the screenshots below for both scenarios.

Such a differentiation is not applied to the button with the default Github theme, ie. when Darkness is disabled. Could the behavior be made consistent?

**Screenshots**
![image](https://user-images.githubusercontent.com/8807030/49564548-ee418400-f949-11e8-9442-8663ef702f3f.png)

![image](https://user-images.githubusercontent.com/8807030/49564654-509a8480-f94a-11e8-9a81-da5bae4a6415.png)

**Comment by TheGooner93** [comment]
In addition to the buttons, this behavior is pretty much for any a tags in Github, for eg. Pull requests, Marketplace, etc in the Header nav bar, and yet again, the visited behavior is not present default Github themes.

**Comment by TheGooner93** [comment]
I've provided a fix here : https://github.com/liorgrossman/darkness/pull/103 . Please have a look @liorgrossman

**Comment by liorgrossman** [comment]
Perfect, thanks @TheGooner93 !
