### ISSUE TITLE
Text fields

### ISSUE THREAD

**Issue by Edwarrdo** [liorgrossman/darkness#101]
* Site: facebook
* Theme: iceberg
* URL: https://www.facebook.com/
* Darkness Version: 2.0.2
* Browser: Chrome 71.0.3578.80
* Operating System: Windows 10
* Resolution: 1920x1080
* Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36

![darkness-bug](https://user-images.githubusercontent.com/26359778/49658968-dbaf7380-fa4b-11e8-92da-eec424f2cd99.png)
Here it shows how the text format doesnt adjust to the theme and it fills the square with white space. It's really annoying. 

![text-bug2](https://user-images.githubusercontent.com/26359778/49659049-08638b00-fa4c-11e8-8266-13a2053bc31a.png)
Here it shows again how the text that shows people who have liked a post is adjusting poorly and can barely be understood.

Can you do something about it?
Thank you for the attention!

**Comment by theme1256** [comment]
This is the same issue as #89, closing
