### ISSUE TITLE
Colors in Google Charts

### ISSUE THREAD

**Issue by TheGooner93** [liorgrossman/darkness#105]
Darkness v2
Chrome
Firefox
Open Source
      
Upgrade
Contact
To report a bug, please:
 
* Site: google
* Theme: iceberg
* URL: https://www.google.co.in/search?q=election+results&oq=election&aqs=chrome.0.0j69i57j0l4.1099j0j1&sourceid=chrome&ie=UTF-8
* Darkness Version: 2.0.0 Pro
* Browser: Chrome 70.0.3538.110
* Operating System: Mac OS X 10_14_1
* Resolution: 1680x1050
* Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
Chrome Extension   ·   Firefox Add-on   ·   GitHub   ·   Pro Upgrade   ·   Contact   ·   Privacy
Darkness is made with love by Lifehack Labs

**Bug Description**
The color of the chart slice differs from the color of the chart slice legend( my guess is its because its inverted). Note: the link above may not be available for long, since it is the result of an election that concluded today ie. 11 Nov 2018

**Screenshots**
Here is the normal expected behavior: 
![image](https://user-images.githubusercontent.com/8807030/49793668-c3956800-fd5b-11e8-8da8-4d2a3ef10f52.png)

Here is the buggy behavior:
![image](https://user-images.githubusercontent.com/8807030/49793701-d14aed80-fd5b-11e8-8751-a80578bdf0e6.png)

**Comment by TheGooner93** [comment]
Could this be linked to https://github.com/liorgrossman/darkness/issues/97 ?

**Comment by TheGooner93** [comment]
@liorgrossman I have provided a fix in https://github.com/liorgrossman/darkness/pull/106

**Comment by theme1256** [comment]
I've merged #106, closing this.
