### ISSUE TITLE
It's nice to have colors to the emphasized tag `<em>` in Google

### ISSUE THREAD

**Issue by khiav223577** [liorgrossman/darkness#109]
**Is your feature request related to a problem you've encountered? Please describe.**

There is no special color for the emphasized text in all themes.

The keyword `Darkness` is red in original theme and other texts are black. But the color for the keyword and other texts are the same in themes provided by Darkness.

### No Theme
![image](https://user-images.githubusercontent.com/4011729/49895133-a90ddc80-fe8a-11e8-8afd-e1ebfb1a5c94.png)

### Iceberg
![image](https://user-images.githubusercontent.com/4011729/49895138-ad39fa00-fe8a-11e8-939e-260a5b893f46.png)

**Describe the solution you'd like to see**
It's nice to have colors to the emphasized tag `<em>`.

**Comment by theme1256** [comment]
Google doesn't highlight in that way when I try that search, it just makes it bold.

But, I've still added a tiny bit of code to highlight it.
