### ISSUE TITLE
Gmail notification pop-up

### ISSUE THREAD

**Issue by mkreilis** [liorgrossman/darkness#117]
The notifications for Gmail are very difficult to read. White text on a bright yellow background. I feel as though the yellow for the notification is out of place its self but a darker font would be helpful.
![image](https://user-images.githubusercontent.com/43114388/50377830-53f06a00-05f2-11e9-84ea-86de68d8c35e.png)

**Comment by liorgrossman** [comment]
Fixed, thanks for reporting
