### ISSUE TITLE
Colour inverted in facebook chat

### ISSUE THREAD

**Issue by XCallender** [liorgrossman/darkness#125]
* Site: facebook
* Theme: redalert
* URL: https://www.facebook.com/
* Darkness Version: 2.0.5 Pro
* Browser: Chrome 71.0.3578.98
* Operating System: Windows 10
* Resolution: 1920x1080
* Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Bug Description**
Facebook updated yesterday and now there are ugly white corners in every text box as well as the colour from text have been inverted.

**Screenshots**
https://gyazo.com/adc5eb54d3a49fdaa2f99fc80bc42b6e

**Comment by drkmm** [comment]
Thanks !
+1

**Comment by theme1256** [comment]
Dublicate of #89
