### ISSUE TITLE
BUG CHAT FACEBOOK

### ISSUE THREAD

**Issue by okradavid** [liorgrossman/darkness#128]
**Bug Information**
* Site: Facebook
* Theme: Material Design
* URL: https://www.facebook.com/
* Darkness Version:  2.0.5 Pro
* Browser: Google Chrome 
* Operating System: Windows 10

**Bug Description**
 The chat is seen with a few white boxes in each one

**Screenshots**
https://imgur.com/a/TIOLqJw

**Comment by theme1256** [comment]
Dublicate of #89
