### ISSUE TITLE
Group chat collors inverted, where transitioning chat collors (blue-pink)

### ISSUE THREAD

**Issue by pauliusrug** [liorgrossman/darkness#129]
* Site: facebook
* Theme: all of them
* URL: https://www.facebook.com/
* Darkness Version: 2.0.6 Pro
* Browser: Chrome 71.0.3578.98
* Operating System: Windows 10
* Resolution: 1600x900
* Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
SC:
http://prntscr.com/m82s4w

**Comment by liorgrossman** [comment]
@theme1256 just fixed this
Uploaded a version to Chrome Web Store & Firefox Store, so it should be available to all users within few hours
