### ISSUE TITLE
Facebook Messenger Gradient Color Bug

### ISSUE THREAD

**Issue by itszerokelvin** [liorgrossman/darkness#131]
**Bug Information**
(visit the affected website → click the moon icon → "Send Feedback" → "Bug Report" → paste here)
* Browser: Chrome 71.0.3578.98
* Operating System: Windows 8.1
* Resolution: 1920x1080
* Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Bug Description**
Please provide a clear description of what the bug or issue is.
Facebook messenger has gradient colors but darkness messes it up.

**Screenshots**
If necessary, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/46802077/51360396-51adee00-1a80-11e9-8411-03856d4d3012.png)

**Comment by theme1256** [comment]
Looks a bit like you have two darkness plugins running at the same time.

It's that or Facebook at already rolling our another version of messenger and I don't have that yet.

Just submitted a couple of changes, so it might be fixed.
