### ISSUE TITLE
Facebook static elements no longer static

### ISSUE THREAD

**Issue by HughPH** [liorgrossman/darkness#139]
* Site: facebook
* Theme: any (except none)
* URL: https://www.facebook.com/
* Darkness Version: 2.0.6 Pro
* Browser: Firefox 64.0
* Operating System: Linux -
* Resolution: 1920x1080
* Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0

**Bug Description**
Applying any theme makes elements no longer 'stick' to the top or bottom of the page - i.e. they scroll up with the rest of the page. Affects header, chat windows, chat list. Also noticed this with a download bar extension which sticks a bar to the bottom of each page: the bar scrolls with the page when a theme is active.

Tried disabling all other extensions.

**Comment by blackthornedk** [comment]
I have the same problem, both on Linux Mint and Windows 10.
Also: The Darkness button to change theme is not visible.
Only way to restore Facebook is to disable the entire add-on.

 * Browser: FireFox 64.0.2
 * Darkness version: 2.0.6
 * Operating System: Linux Mint 19.1 & Windows 10 1803

**Comment by theme1256** [comment]
This is a dublicate of #81, closing
