### ISSUE TITLE
white square still around emojis

### ISSUE THREAD

**Issue by tonyyang924** [liorgrossman/darkness#150]
**Bug Information**

* Site: facebook
* Theme: all
* Darkness Version: 2.0.13
* Browser: Google chrome
* Operating System: Windows 10

**Bug Description**
long click emoji shows white background emoji in chat room

**Screenshots**
![background_white](https://user-images.githubusercontent.com/12247447/52530728-5f375a80-2d44-11e9-8dca-15ec4f520a6b.png)

**Comment by theme1256** [comment]
I can't reproduce this in full.

It only happens while long-clicking and disappears when I release the mouse.
This makes it very difficult to debug.

**Comment by tonyyang924** [comment]
@theme1256 Yes, when you release the mouse white square will disappears. The problem still shows up in version '2.0.18'. 

It's hard to fix unless the emoji button can be clicked without click the mouse and check class name in console.
