### ISSUE TITLE
Port to Android?

### ISSUE THREAD

**Issue by TheAlienDrew** [liorgrossman/darkness#158]
I'd love to see this working on Android... If this happens, I'll definitely look into buying the property features.

**Comment by liorgrossman** [comment]
As far as I know, browser extensions are not supported on Chrome for Android.
Therefore, it's currently impossible to make Darkness work on Android.

**Comment by TheAlienDrew** [comment]
It's not impossible, at least for Firefox. I "fixed" my problem by
installing the extension in Firefox Mobile. Might want to mention this
somewhere on the main website for users that want to use Dark Reader on
mobile.

**Comment by liorgrossman** [comment]
Ah, sorry.
I mistakingly assumed you meant Chrome on mobile.
Yes, the extension should theoretically work on Firefox Mobile, but unfortunately it was never tested. I hope it's fully functional.

**Comment by TheAlienDrew** [comment]
That's what I'm saying! Haha, it seems to be fully functional. So far it is
working fine just like on the desktop. So, maybe include that mobile is
indirectly supported when using Firefox Mobile on the main webpage
somewhere? (that way others don't have to make issues on the Github).
