### ISSUE TITLE
Darkness not needed for this site?

### ISSUE THREAD

**Issue by TheAlienDrew** [liorgrossman/darkness#159]
Gmail doesn't need the theme, because anyone can just pick the internal dark theme that Google offers. The only point to this theme I could see for now, is just theming everyone's personal when they open an email.

**Comment by theme1256** [comment]
That is true, I don't use Darkness on Gmail, I use the "Terminal" theme.

But! some think that that theme is still too bright or might want other elements styled as well.
We won't be removing support in the near future.
