### ISSUE TITLE
Chrome Web Store URL doesn't work

### ISSUE THREAD

**Issue by crscaballero** [liorgrossman/darkness#160]
**Bug Information**
* Site: https://darkness.app/
* URL: https://chrome.google.com/webstore/detail/darkness-beautiful-dark-t/imilbobhamcfahccagbncamhpnbkaenm

**Bug Description**
My installation is corrupted, and when i looking for in the market for re install again, the link in official web site doesn't work

**Screenshots**
![Screen Shot 2019-03-18 at 11 22 44](https://user-images.githubusercontent.com/21251229/54553774-31ab8580-4970-11e9-82a2-4d59fc1789f7.png)

![Screen Shot 2019-03-18 at 11 26 14](https://user-images.githubusercontent.com/21251229/54554003-a7afec80-4970-11e9-9a46-2422118f76ef.png)

**Comment by liorgrossman** [comment]
Indeed.
Chrome Web Store reported there's a problem with the description of the extension (still not sure what the exact problem is!) - so the extension was taken down.
I'm corresponding with the Chrome Web Store team to try and figure this out.
Once I figure out what's wrong with the description, I'll fix and send it to review again.
This would probably take a couple of days, sorry about that. Wish I could do something to expedite this process.

**Comment by jsquire** [comment]
For those experiencing this and are looking for a work-around until the Chrome store issue is resolved, I was able to bypass the corruption status and enable the extension again by side-loading my existing installation as an unpacked extension.   The downsides to this approach are that Chrome will occasionally nag about the dangers of developer mode extensions, and returning to the official Chrome store version is likely to require uninstalling and reinstalling the extension.

### Step by Step
   - Enable `Developer mode` by navigating to `chrome://extensions` and flipping the toggle on the right hand side of the header.
![image](https://user-images.githubusercontent.com/913445/54753010-58f39400-4bb6-11e9-8612-78c81d385f6b.png)

  - In the same extensions management screen, clock the `Load unpacked` button in the upper-left.
![image](https://user-images.githubusercontent.com/913445/54753095-935d3100-4bb6-11e9-878a-f197c47a8742.png)

  - Point the file dialog that opens at the root of the existing Darkness extension, where the file `manifest.json` exists.   For a standard Chrome installation on Windows, this will be under  your `%AppData%\Local\Google\Chrome\User Data\<<PROFILE NAME OR DEFAULT>>\Extensions` directory. 
![image](https://user-images.githubusercontent.com/913445/54753332-28602a00-4bb7-11e9-959e-af6f27f7ad3c.png)

  - After pressing `Select Folder` on the dialog, the extension should be enabled and working again and indicate that it was side-loaded.
![image](https://user-images.githubusercontent.com/913445/54753685-0915cc80-4bb8-11e9-9351-da3a67c9f083.png)
![image](https://user-images.githubusercontent.com/913445/54753468-7ffe9580-4bb7-11e9-8dd2-794a3fb49ecf.png)

**Comment by liorgrossman** [comment]
Thanks @jsquire 

I'm happy to report that Darkness is now back on Chrome Web Store
https://chrome.google.com/webstore/detail/darkness-beautiful-dark-t/imilbobhamcfahccagbncamhpnbkaenm

There was a problem with the description on Chrome Web Store, and therefore the extension was taken down abruptly.
I think the source was one of the lines in the description which contained a list of supported websites (Google, Facebook, YouTube, Gmail, Google Drive, Twitter, Facebook Messenger, Instagram, Reddit...). This line was probably automatically flagged as excessive use of keywords, as it has a lot of commas and looks like keywords stuffing.
I made this line significantly shorter, and now the extension has been reinstated.
