### ISSUE TITLE
Facebook videos start with black colors 

### ISSUE THREAD

**Issue by VYNARICOD** [liorgrossman/darkness#165]
**Bug Information**
(visit the affected website → click the moon icon → "Send Feedback" → "Bug Report" → paste here)
* Site: facebook
* Theme: iceberg
* URL: https://www.facebook.com/
* Darkness Version: 2.0.22
* Browser: Chrome 73.0.3683.86
* Operating System: Windows 10
* Resolution: 1920x1080
* Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

**Bug Description**
When loading a video on facebook, mostly on live transmissions, the video will first load on an all black image with some outerlines of the image on diferent colors, and after a couple of seconds it will turn back to it's original image color.

**Screenshots**
![image](https://user-images.githubusercontent.com/49348237/55673294-65891500-5863-11e9-8197-51fd2c1de849.png)

**Comment by theme1256** [comment]
I can't replicate this.  
I guess that it's a sideeffect of the way Facebook loads videos.  
When a theme isn't enabled my guess is that it shows a white background, but you don't notice because it's inside another white element.
