### ISSUE TITLE
Quora header not staying fix

### ISSUE THREAD

**Issue by blackdevil72** [liorgrossman/darkness#167]
**Bug Information**
* Site: quora
* Theme: none
* URL: https://www.quora.com/
* Darkness Version: 2.0.22 Pro
* Browser: Firefox 66.0
* Operating System: Linux -
* Resolution: 2560x1440
* Agent: Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0: 

**Bug Description**
When a theme is applied the Quora header doesn't stay fixed on the top any more it goes up when scrolling down.

**Screenshots**
![quora1](https://user-images.githubusercontent.com/1483343/55741365-61105800-5a2d-11e9-9971-2f0f1f4ac1c5.png)
![quora2](https://user-images.githubusercontent.com/1483343/55741372-62da1b80-5a2d-11e9-9d21-c20b7bd3d1aa.png)

**Comment by theme1256** [comment]
This is probably the same issue as #81.

Is it also an issue in Chrome?

**Comment by blackdevil72** [comment]
I don't know I don't use chrome. I'll check that later.

Just as a note I have the same problem with facebook as #81

**Comment by blackdevil72** [comment]
Hello,

I think it maybe related to #81, I tried with chromium and everything was good (both Quora and Facebook).

**Comment by liorgrossman** [comment]
Since it's related to #81, I'm closing this issue, and will add a note on #81 that this bug affects Quora as well. Thanks for reporting this.
