### ISSUE TITLE
Please support dark theme for the mobile facebook. 

### ISSUE THREAD

**Issue by lisagilliland88** [liorgrossman/darkness#169]
**Is your feature request related to a problem you've encountered? Please describe.**
Please provide a concise description of what the problem is. e.g. I'm always frustrated when [...]

**Describe the solution you'd like to see**
A clear description of the solution you'd like to see

**Comment by liorgrossman** [comment]
Hi Lisa.
Unfortunately, not many people use the mobile Facebook with Darkness, so I don't believe we will support it in the foreseeable future.
I hope you understand.
