### ISSUE TITLE
blue square around profile google account photo 

### ISSUE THREAD

**Issue by bugstuck** [liorgrossman/darkness#173]
https://imgur.com/gallery/kHOMvlF

**Comment by tiborrr** [comment]
Some additional info
* Site: google
* Theme: iceberg
* URL: https://www.google.nl/search?ei=mWIfXbiQDcndwQK7maCICA&q=test&oq=test&gs_l=psy-ab.3..0j0i67j0j0i67j0j0i67j0l4.293962.294263..294841...0.0..0.68.244.4......0....1..gws-wiz.......0i71j35i39i19j35i39j0i131j0i131i67.cYc9qy4Yhi8
* Darkness Version: 2.0.25
* Browser: Chrome 75.0.3770.100
* Operating System: Windows 10
* Resolution: 1920x1200
* Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

**Comment by theme1256** [comment]
Fixed in 84816da
