### ISSUE TITLE
An option to hide moon icon

### ISSUE THREAD

**Issue by VucoPL** [liorgrossman/darkness#174]
Hello,

I'd like to make a suggestion of adding an option to hide the moon icon in the top-right corner of the browser. In my opinion the menu that's appearing after clicking the icon should be available from the icon that's put in the browser toolbar. I think that having two icons nearly in the same place is pointless. The main thing that annoys me here is that the icon is still visable when going into full screen mode in YT for example. If the icon really has to stay, at least please make it invisible when going into full screen mode.
Sincerely,

VucoPL

**Comment by gibant1** [comment]
Agreed, when you go full screen the icon on the top right should disappear.

**Comment by theme1256** [comment]
Just a note, the thing with the icon appearing over the full-screen YT, has been fixed, see #90.  
It just hasn't been published to the app on the chrome store.

**Comment by liorgrossman** [comment]
Published a new version to the store, closing
