### ISSUE TITLE
What is missing is a Beige/ Sepia theme color 

### ISSUE THREAD

**Issue by anth11** [liorgrossman/darkness#175]
A Beige/ Sepia theme would make it great for reading during day time, honestly I thought purchasing the app would at least have that one, but it's not on the app at all unfortunately.

**Comment by liorgrossman** [comment]
The coffee theme has exactly those colors (Beige, Sepia), please see below
<img width="1304" alt="2019-05-25_1404" src="https://user-images.githubusercontent.com/987284/58374626-318eaf80-7ef6-11e9-8b32-25dd5261f354.png">

**Comment by anth11** [comment]
Hi,

That is dark brown, in the background. I meant for beige to be in the
background, as on the right side in the big thumbnail.

**Comment by liorgrossman** [comment]
Ah, I understand now.
Darkness, as the name implies, is focused on dark themes.
That means the background on all themes is black, or close to black (very dark colors).
It is frankly unlikely that we'll introduce color themes with a bright background (such as beige), I'm sorry for that.
