### ISSUE TITLE
Editing existing Themes easily

### ISSUE THREAD

**Issue by TechnikTim** [liorgrossman/darkness#178]
It would be very handy if you can change the colours yourself. So a kind of settings menu on each page where RGB values ​​can be adjusted. I imagine that to be similar to Telegram. There you can also create your own design. You can customize any icon, any text, ... as you would like it.
This would be very cool.

**Comment by liorgrossman** [comment]
Hi Tim. Thanks for the feedback. A similar suggestion is discussed in #86
