### ISSUE TITLE
Fix New Google Images

### ISSUE THREAD

**Issue by VantaB** [liorgrossman/darkness#180]
Recently, the way Google Images presents a preview of an image has been changed so it is to the right of the other results, rather than creating a bar in between them. However, without the Darkness theme, this bar **is already** dark themed. With any Darkness theme on, the preview bar is bright white.

This results in this sizeable part of the screen being less attractive in a Darkness theme than without.

I believe an easy fix is to simply not apply the theme to this bar, as it is fine without. Or ensuring the preview bar in Google Images conforms accurately to the Darkness theme in use. Examples attached.
With Darkness theme:
![image](https://user-images.githubusercontent.com/54244983/63227639-920c5080-c1b6-11e9-8810-5765cb922e7d.png)
Without Darkness theme:
![image](https://user-images.githubusercontent.com/54244983/63227651-b23c0f80-c1b6-11e9-9d73-772a00590653.png)

**Comment by theme1256** [comment]
I fixed this in 8e6e04f638bee72b1dc99928e8549e9d47b2b3c6
