### ISSUE TITLE
Missing extension in Firefox Add-on Store

### ISSUE THREAD

**Issue by absolutjdv** [liorgrossman/darkness#181]
**Bug Information**
(visit the affected website → click the moon icon → "Send Feedback" → "Bug Report" → paste here)
* Site: 
* Theme: 
* URL: 
* Darkness Version: 
* Browser: 
* Operating System: 

**Bug Description**
Please provide a clear description of what the bug or issue is.

**Screenshots**
If necessary, add screenshots to help explain your problem.

**Comment by theme1256** [comment]
Please expand on what you actually want, that is quite the bare "bug report"

**Comment by hukitan** [comment]
What he/she means, is that there's no extension in the Mozilla Add-on store
as you can corroborate here https://addons.mozilla.org/en-US/firefox/addon/darkness-dark-themes/

**Comment by liorgrossman** [comment]
I can confirm.
Darkness on Firefox has been disabled on the Mozilla addons store.
Mozilla's addons store has new restrictions as to what is disallowed within extension code (interaction with DOM, remote scripts, etc.)
I'm trying to figure out how to remedy it, as this would require many changes to the extension code *facepalm*

**Comment by hukitan** [comment]
Can I suggest making the .xpi file and publish on the website?
Well, meanwhile something better appears

**Comment by absolutjdv** [comment]
Yes please, it would be awesome if Darkness on Firefox can be enabled again in the Mozilla addons store. I've tried other extensions like Dark Mode, Dark Reader etc., but none come close to Darkness. Love the way it changes my Google, Facebook experience.
Kudos to the developers!

**Comment by shim3d** [comment]
Is someone able to compile this for firefox? I am too nooby at git

**Comment by absolutjdv** [comment]
Not yet... I'm also n00b and waiting for the extension

**Comment by longnd** [comment]
hi @absolutjdv could we have some updates regarding this issue?

**Comment by absolutjdv** [comment]
Yes the Darkness extension for Firefox Version 71.0 (64-bit) is missing.

**Comment by absolutjdv** [comment]
![darkness-dark-themes](https://user-images.githubusercontent.com/54226279/70883428-c83acf00-1ff4-11ea-8b49-73896abd9fba.PNG)

**Comment by DanielContreras** [comment]
It is missing, but if you temporarily (while, hopefully, this gets fixed) install the developer version and follow the instructions on the readme it does actually work. But it doesn't persist after exiting firefox due to it being a temporary plugin.

**Comment by laicheungkee** [comment]
This extension is still missing, of course I do understand the developers must know it ... I would like to get notification when it is back online again, so that I could get the Pro version as what I did on Chrome.

**Comment by liorgrossman** [comment]
Definitely aware of that!
Trying to wrap my head around how to solve all the things the Mozilla review teams wants us to fix, this is really annoying.
I'll update this issue as soon as we have progress on that front.

**Comment by Gitoffthelawn** [comment]
I don't know if this will help at all, but looking at the code of these two extensions may help you:  

https://github.com/darkreader/darkreader
https://github.com/timmyRS/Universal-Bypass

BTW, you may want to remove the invalid tag from this issue. :)

**Comment by liorgrossman** [comment]
Thanks!
Indeed, I removed the "invalid" tag, this is definitely a valid issue

**Comment by liorgrossman** [comment]
Just an update here:
Firefox add-ons store has added new restrictions a while ago as to what is disallowed within the add-on code (interaction with DOM, remote scripts, etc.), and has therefore disabled the Darkness add-on.
Making Darkness comply with the Firefox add-ons store policy would require significant changes to the add-on code, so realistically, it is unlikely that we will re-publish it on the Firefox store.
Firefox will still be supported if you install the extension locally, as described in the README, but not available in the add-on store.
I have updated the README and the site to reflect that, but please let me know if I have missed anything.

**Comment by Gitoffthelawn** [comment]
@liorgrossman Thanks for your update!

What specific functions does Darkness have that are not allowed within the AMO store?

AFAIK, there are scores (perhaps hundreds) of popular extensions in the store that interact with the DOM.

Remote scripting would definitely be a no-no, for obvious reasons.  I have never tried Darkness (it's on my list of extensions to try), so I haven't reviewed its code yet.  Does it call remote scripts?

Anything else that would preclude Darkness from being in AMO?
