### ISSUE TITLE
No se ve miniatura de Apps de Google

### ISSUE THREAD

**Issue by lobogris26** [liorgrossman/darkness#182]
**Bug Information**
(visit the affected website → click the moon icon → "Send Feedback" → "Bug Report" → paste here)
* Site: 
* Theme: 
* URL: 
* Darkness Version: 
* Browser: 
* Operating System: 

**Bug Description**
Please provide a clear description of what the bug or issue is.
En la página del buscador, no se ve la miniatura d las Apps de Google.

**Screenshots**
If necessary, add screenshots to help explain your problem.
![2019-08-28 04 00 28 www google com de863f5f7e76](https://user-images.githubusercontent.com/24557216/63833095-86ecb980-c948-11e9-9834-064796b0fff5.png)

**Comment by theme1256** [comment]
Fixed in 84816da
