### ISSUE TITLE
In Google Chrome for Mac, Google Calendar "Today" and the right and left arrows for moving forward and backward are not visible with any of your themes.

### ISSUE THREAD

**Issue by wwelsh39** [liorgrossman/darkness#185]
In Google Chrome for Mac, Google Calendar "Today" and the right and left arrows for moving forward and backward are not visible with any of your themes. Wayne Welsh wwelsh1939@gmail.com

* Site: Google Calendar
* Theme: Non of the themes show the "Today" or the right and left arrows
* URL: https://calendar.google.com/calendar/r/customday?hl=en&tab=wc
* Darkness Version: https://calendar.google.com/calendar/r/customday?hl=en&tab=wc
* Browser: Google Chrome for Mac
* Operating System: Mac OS 10.14.6
![Screen Shot 2019-09-06 at 3 17 47 PM](https://user-images.githubusercontent.com/55000785/64454918-326cdb00-d0ba-11e9-93a0-cfc29bc507d6.png)
![Screen Shot 2019-09-06 at 3 17 33 PM](https://user-images.githubusercontent.com/55000785/64454931-37ca2580-d0ba-11e9-928c-07464f346a4a.png)

**Bug Description**
Please provide a clear description of what the bug or issue is.

**Screenshots**
If necessary, add screenshots to help explain your problem.

**Comment by theme1256** [comment]
This is just one of many active issues on the Google-sites that we support.  
Might have a look at it later.
