### ISSUE TITLE
Trello Board Menu

### ISSUE THREAD

**Issue by Thingiess** [liorgrossman/darkness#191]
Darkness theme works wonderful on Trello, except whe  you click on the "board" label, it's displayed with colors that are super hard to see:

![trello](https://user-images.githubusercontent.com/55908280/65812512-c8a59580-e17c-11e9-9799-d521fed97b59.png)

The suggestion would be to use a more eye friendly color for that menu 
Thank you in advance! :D

**Comment by theme1256** [comment]
I've made some changes, it's Trello that does some weird stuff, but it should be fixed now (in b162a8f0eb9784899e6934e5c4ce8dfeab8dfb0f)
