### ISSUE TITLE
how many days before we get pro ?

### ISSUE THREAD

**Issue by sirius1** [liorgrossman/darkness#195]
paid for, no pro yet, just refund please  

Receipt from Darkness |  
-- | --

AMOUNT PAID
$2.99
DATE PAID
November 5, 2019

**Comment by liorgrossman** [comment]
Hi Sirius.
I cannot see the file you've attached.
Can you please forward the email your got with the receipt to support@darkness.app
You should get pro immediately, so once you send me the receipt, I'll help you activate it.

**Comment by sirius1** [comment]
i did forward the e-mail twice already, how many copies do you need ?  why not simply reimburse my visa
rejwow A yahoo.c


-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
AMOUNT PAID$2.99 | AMOUNT PAID | $2.99 |   | DATE PAIDNovember 5, 2019 | DATE PAID | November 5, 2019 |   | PAYMENT METHOD – 6xxx | PAYMENT METHOD | – 6xxx
AMOUNT PAID
$2.99
DATE PAID
November 5, 2019
PAYMENT METHOD
– 6xxx

**Comment by sirius1** [comment]
anyway you'll be flagged as a thief on google store,   you're lame

**Comment by liorgrossman** [comment]
I've just refunded you, and also sent you activation instructions.
Please check your email.

**Comment by sirius1** [comment]
never got the activation instructions... anyway, thanks for the refund
