### ISSUE TITLE
no pro but paid for

### ISSUE THREAD

**Issue by sirius1** [liorgrossman/darkness#196]
i did forward the e-mail twice already, how many copies do you need ? why not simply reimburse my visa
rejwow A yahoo.c  .....Windows 10 64

-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
AMOUNT PAID$2.99 | AMOUNT PAID | $2.99 |   | DATE PAIDNovember 5, 2019 | DATE PAID | November 5, 2019 |   | PAYMENT METHOD – 6xxx | PAYMENT METHOD | – 6xxx
AMOUNT PAID
$2.99
DATE PAID
November 5, 2019
PAYMENT METHOD
– 6xxx

$4.04 Canadian

anyway, nothing is moving in the  right direction so you'll be flagged and reported as a thief on google store

**Comment by liorgrossman** [comment]
I've just refunded you, and also sent you activation instructions.
Please check your email.
