### ISSUE TITLE
Live video color inverted

### ISSUE THREAD

**Issue by jordanpurinton** [liorgrossman/darkness#21]
I was using this the other day and noticed that a live video feed on Twitter was showing up as inverted.

**Comment by jordanpurinton** [comment]
Here's a screenshot with the described issue:
![screen shot 2016-12-06 at 2 06 07 pm](https://cloud.githubusercontent.com/assets/12102971/20943574/45aa914a-bbbd-11e6-981d-fade179566fe.png)

**Comment by jordanpurinton** [comment]
Think I found the issue.
I think if we include :

```
.player-container{
    @include invert-back();
}
```
in the `twitter.scss` file that should solve the issue. 

![screen shot 2016-12-06 at 3 24 55 pm](https://cloud.githubusercontent.com/assets/12102971/20946655/d25be6ec-bbc8-11e6-8096-f99f2bd52e63.png)

**Comment by jordanpurinton** [comment]
PR here https://github.com/liorgrossman/darkness/pull/22

**Comment by liorgrossman** [comment]
I've been kind of swapmed, thanks for debugging and fixing it, I've merged the pull request.
Welcome to the Darkness contributors family :)
