### ISSUE TITLE
Lost Pro Migrating to Brave Browser (Chromium-based)

### ISSUE THREAD

**Issue by DMC-UK** [liorgrossman/darkness#215]
Hi guys,
As the title says, I'm moving over from Chrome to Brave (or at least giving it a fair shakedown!), which is an open source, Chromium-based browser, so it's installed Darkness fine, but it's not recognised my Pro status. Is it possible to get it to work on this browser or would I have to re-purchase?
Thanks,
-Dan.

**Comment by liorgrossman** [comment]
Hey Dan.
We haven't tested Darkness on Brave browser, so can't guarantee it will work.

Nevertheless, please send me an email to support@darkness.app and I'll send over instructions to reactivate your Pro version. you don't need to repurchase it.

Best,
Lior
