### ISSUE TITLE
Darkness Pro purchased - no validation or activation email ever received - money paid.

### ISSUE THREAD

**Issue by ball1201** [liorgrossman/darkness#216]
**Bug Information**
(visit the affected website → click the moon icon → "Send Feedback" → "Bug Report" → paste here)
* Site:  All sites
* Theme:   Darkness Pro
* URL: 
* Darkness Version: 
* Browser: Google Chrome
* Operating System: Windows 10

**Bug Description**
There is nothing I can find with which to configure the Darkness Pro colors and themes.  When I click the "moon" like it says to do, nothing happens - this is all I get:  

**Screenshots**

![image](https://user-images.githubusercontent.com/67381771/85588256-8b3d3e00-b610-11ea-88f9-edc2083a9033.png)

**Comment by liorgrossman** [comment]
Hi there,
Not sure what went wrong here.
Can you please email me with your receipt to support@darkness.app ?

**Comment by Klaus-dev78** [comment]
U mnie to samo nie aktywuje sie subskrypcja i nie można pobrac wiecej wtyczek z tematami.

**Comment by liorgrossman** [comment]
@Klaus-dev78 Please email me at support@darkness.app and I'll help
