### ISSUE TITLE
not the correct access rights...

### ISSUE THREAD

**Issue by Julix91** [liorgrossman/darkness#23]
While installing the dev version, this didn't work for me:

5. Set up a the original repo as a remote: `git remote add upstream git@github.com:liorgrossman/darkness.git`
6. Get the code: `git fetch upstream`

It complained I didn't have the correct access rights. 

Same was true for `git clone git@github.com:YOUR_GITHUB_USER/darkness.git`, so then I used `git clone https://github.com/YOUR_GITHUB_USER/darkness.git` and it worked.

Didn't think to similarly change the url for the upstream before I already had npm installed / got darkness into Chrome.

At some point I'll do it again and properly, until then if the permission thing is an issue that others would also have, and if as I suspect `git remote add upstream https://github.com/liorgrossman/darkness.git` would have worked, it might be worth changing that in the Readme...

**Comment by liorgrossman** [comment]
Good catch! 👍 
I will merge the pull request now.
