### ISSUE TITLE
negative image

### ISSUE THREAD

**Issue by nicolasDitWolfwood** [liorgrossman/darkness#232]
**Bug Information**
(visit the affected website → click the moon icon → "Send Feedback" → "Bug Report" → paste here)
* Site: 
* Theme: 
* URL: 
* Darkness Version: 
* Browser: 
* Operating System: 

hello, since the last update, on trello all the themes work fine, but they show all the images as attachments, in negative. which is very embarrassing.
how to change that?
thanks in advance.

**Comment by theme1256** [comment]
I can't reproduce this.  
Please provide a screenshot, and information about your browser (your post describes how to do that)
