### ISSUE TITLE
Theme Config Not Detected/Available for Several Websites

### ISSUE THREAD

**Issue by ndcorc** [liorgrossman/darkness#234]
**Bug Information**
I payed for the Pro version yet the extension is not detecting both standard and pro version websites

* Sites:
   1.) Google
   2.) Google Drive
   3.) YouTube
   4.) Google Keep
   5.) Google Photos
   6.) Gmail
   7.) Google Contacts
   8.) ShareLaTex / CloudLeaf
* Browser: 
   - Chrome
* Operating System: 
   - macOS Catalina

**Bug Description**
As seen in the example screenshots, the sites listed above are not being detected by the extension (missing the moon icon)

**Screenshots**
<img width="1792" alt="Screen Shot 2020-12-06 at 11 26 57 PM" src="https://user-images.githubusercontent.com/12104605/101313421-b791f300-381b-11eb-93e7-f891af988d89.png">
<img width="1792" alt="Screen Shot 2020-12-06 at 11 27 03 PM" src="https://user-images.githubusercontent.com/12104605/101313459-c7113c00-381b-11eb-8cfd-0280acb6beff.png">
<img width="1792" alt="Screen Shot 2020-12-06 at 11 27 07 PM" src="https://user-images.githubusercontent.com/12104605/101313485-d2646780-381b-11eb-8ecc-f3071b6fadfe.png">
<img width="1792" alt="Screen Shot 2020-12-06 at 11 27 22 PM" src="https://user-images.githubusercontent.com/12104605/101313510-e740fb00-381b-11eb-9b59-94fdb2dfc6a1.png">
<img width="1792" alt="Screen Shot 2020-12-06 at 11 28 03 PM" src="https://user-images.githubusercontent.com/12104605/101313541-f4f68080-381b-11eb-9a60-b33e864189a7.png">
<img width="1792" alt="Screen Shot 2020-12-06 at 11 28 18 PM" src="https://user-images.githubusercontent.com/12104605/101313567-02ac0600-381c-11eb-8ed6-844e674e3691.png">
![Uploading Screen Shot 2020-12-06 at 11.29.45 PM.png…]()

**Comment by liorgrossman** [comment]
Really strange, based on the screenshot it seems like Darkness doesn't activate for you at all (I cannot see the moon icon in the screenshot).
Can you please send me an email to support@darkness.app? If we're unable to get to the bottom of it, I'll issue you a full refund, of course.
