### ISSUE TITLE
Your darkness themes are not showing up on all me sites. It's available with the little moon in the upper right corner, but when I choose any of the darkness options my page doesn't change

### ISSUE THREAD

**Issue by ghost** [liorgrossman/darkness#235]
**Bug Information**
(visit the affected website → click the moon icon → "Send Feedback" → "Bug Report" → paste here)
* Site: 
* Theme: 
* URL: 
* Darkness Version: 
* Browser: 
* Operating System: 

**Bug Description**
Please provide a clear description of what the bug or issue is.

**Screenshots**
If necessary, add screenshots to help explain your problem.

**Comment by liorgrossman** [comment]
Hi there.
What site do you have this problem with?
Does Darkness dark themes for you on google.com for example?
