### ISSUE TITLE
Facebook Messenger Chat background inverted

### ISSUE THREAD

**Issue by nicolaiwork** [liorgrossman/darkness#236]
* Site: messenger
* Theme: iceberg
* URL: https://www.messenger.com/t/100006471452565
* Darkness Version: 2.0.25 Pro
* Browser: Chrome 87.0.4280.88
* Operating System: Windows 10
* Resolution: 1920x1080
* Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Bug Description**
It seems like Messenger.com have changed some of the styling for the chat 

**Screenshots**
If necessary, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/23095600/101753903-73307c80-3ad3-11eb-8885-a1fe34a80aa8.png)

**Comment by theme1256** [comment]
Those are not the "Iceberg" colors, so I'm guessing that you have multiple plugins enabled.

**Comment by theme1256** [comment]
Ok, messenger is aparently rolling this update out slowly...
I got it now, on my desktop.

**Comment by nicolaiwork** [comment]
@theme1256 thank you for the fast fix! 🥇 

Where can I see the releases, and do I need to do something to update my extension? :)

**Comment by theme1256** [comment]
I cant create a new release, only @liorgrossman can do that.
So you'll have to wait a little bit before it is ready, unless you are running the development version, then you just pull and compile the newest version :)

**Comment by liorgrossman** [comment]
Thanks @theme1256 !
I'll upload a new version to Chrome Web Store early next week
@nicolaiwork - you shouldn't do anything, it'll automatically update on your Chrome (Chrome Extension automatically update every few hours)
