### ISSUE TITLE
Darkness vanishes as you scroll through Twitter

### ISSUE THREAD

**Issue by MelToast** [liorgrossman/darkness#237]
* Site: twitter
* Theme: coffee
* URL: https://twitter.com/home
* Darkness Version: 2.0.25 Pro
* Browser: Chrome 87.0.4280.88
* Operating System: Linux -
* Resolution: 1366x768
* Agent: Mozilla/5.0 (X11; CrOS x86_64 13505.63.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
**Bug Description**
Twitter doesn't retain darkness as you scroll you end up with both sides of the page back to the default/white background while the font/lettering is still set to the darkness, making it impossible to read, while the center of the page, as you scroll, remains dark. 

**Screenshots**
If necessary, add screenshots to help explain your problem.

**Comment by theme1256** [comment]
Dublicate of #221
