### ISSUE TITLE
suggestion: visible elements

### ISSUE THREAD

**Issue by gtapiasgt** [liorgrossman/darkness#239]
Hi,

It would be nice if we could have an option with the same amount of visible elements.

The gmail logo and the search bar buttons now have a visible background (not matching the shape of the search bar shape).

If left with the original amount of elements (backgrounds transparent), that would be a nice option to have.

Thanks!

![Screenshot 2021-01-04 132615](https://user-images.githubusercontent.com/43735331/103571694-fb1a6400-4e90-11eb-9860-ffdb0972122c.jpeg)

**Comment by theme1256** [comment]
Yeah, that is what maintainers of this project do. They fix the theme, when a websites update their design.
