### ISSUE TITLE
Firefox Extension Unavailable

### ISSUE THREAD

**Issue by trirpi** [liorgrossman/darkness#243]
**Bug Information**
On any browser.

**Bug Description**
The firefox extension seems to be removed from the Firefox add-ons website. The link on the website refers to https://addons.mozilla.org/en-US/firefox/addon/darkness-dark-themes/ which does not work and results in the screen:

**Screenshots**
![image](https://user-images.githubusercontent.com/16321928/106400035-59991a80-641c-11eb-9e8a-11e440dbb56b.png)

**Comment by liorgrossman** [comment]
That is correct - thanks for pointing that out.
Darkness on Firefox has been disabled on the Mozilla addons store a while ago.
Mozilla's addons store has new restrictions as to what is disallowed within the extension code (interaction with DOM, remote scripts, etc.), which would require a lot of changes to the extension code, so it is unlikely that we will re-publish it on the Firefox store.
I have just removed all mentions and links to the Firefox add-on store, but please let me know if I've missed anything.

**Comment by FriGiN** [comment]
literally the main page says to get it for firefox.. https://darkness.app/ including screen shot [link](https://1drv.ms/u/s!As51Z58ByZWEnapa0KodglrX49kbTQ)

**Comment by liorgrossman** [comment]
Damn - I missed this one because on Chrome that very same button said "Get Darkness for Chrome".
Thanks for pointing that out!
Fixed and deployed
