### ISSUE TITLE
negative trello image

### ISSUE THREAD

**Issue by nicolasDitWolfwood** [liorgrossman/darkness#245]
**Bug Information**
(visit the affected website → click the moon icon → "Send Feedback" → "Bug Report" → paste here)
* Site: trello.com
* Theme: coffee but everyone else too
* URL: 
* Darkness Version: 2.2.26
* Browser: chrome v 89.0.4389.114
* Operating System: win 7 64bits sp1

**Bug Description**
all photos in trello cards are in negative color

**Screenshots**
original download ![trello-1847211365](https://user-images.githubusercontent.com/73930371/113284232-a056a400-92e9-11eb-8d3e-3b81b81e5c31.jpg)
capture of what we see 
![capture trello probleme](https://user-images.githubusercontent.com/73930371/113284415-e27fe580-92e9-11eb-983d-b00078a000b6.png)

* Browser: Chrome 89.0.4389.114
* Operating System: Windows 7
* Resolution: 1920x1200
* Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36

**Comment by theme1256** [comment]
Hi
I can't seem to reproduce this.

Please tell me what background the board is using.  
Trello has different themes based on the darkness levels of the background, which usually is the culprit and I really don't feel like checking all of them right now.

**Comment by theme1256** [comment]
Closing due to no response
