### ISSUE TITLE
Ms.

### ISSUE THREAD

**Issue by hollyjorose** [liorgrossman/darkness#251]
**Bug Information**
(visit the affected website → click the moon icon → "Send Feedback" → "Bug Report" → paste here)
* Site: 
* Theme: 
* URL: 
* Darkness Version: 
* Browser: 
* Operating System: 

**Bug Description**
Please provide a clear description of what the bug or issue is.

**Screenshots**
If necessary, add screenshots to help explain your problem.
I cannot get the Darkness app to load the No Theme mode. Should I remove Darkness from my laptop and then reload it or can you resolve my problem at your end?

**Comment by liorgrossman** [comment]
Hi there!
Please see here for a solution how to disable color theme:
https://github.com/liorgrossman/darkness/issues/250#issuecomment-1003795114
