### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by age21github** [liorgrossman/darkness#262]
* Browser: Chrome 114.0.0.0
* Operating System: Windows 10
* Resolution: 2560x1440
* Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

White background from yesterday.

**Comment by cwhitesel** [comment]
See https://github.com/liorgrossman/darkness/issues/261

**Comment by age21github** [comment]
Great! Thank you. I didn't think it the same problem from its title.
