### ISSUE TITLE
Multiple inverted colors

### ISSUE THREAD

**Issue by Californ1a** [liorgrossman/darkness#37]
Chrome version 56
YouTube "Tomorrow" theme
GitHub "Iceberg" theme
Twitter "Tomorrow" theme

- On YouTube, click on the playbar as if to scrub through a video, but drag up instead of left or right. This might only be a feature on long videos, but when dragging up on the scrubber, it [displays video thumbnails](http://i.imgur.com/Fn3AwAX.png). All of this interface should not have inverted colors.
- On GitHub, the label colors are inverted and shouldn't be. This is especially confusing [when adding new labels](http://i.imgur.com/LOfYYgp.png) because you have to get the inverse color of what you want.
- On Twitter, all videos and gifs are inverted when they shouldn't be. The gifs that show up with the "add a gif" button aren't inverted until you mouseover them (when they start playing). For videos, both the thumbnail and video itself are inverted and shouldn't be.

**Comment by theme1256** [comment]
I don't really use twitter, but I'm going to take a look at these :)

**Comment by liorgrossman** [comment]
Masterfully fixed by @theme1256 - I've merged the fixes and will be pushing a version to Chrome Web Store later tonight.

**Comment by Californ1a** [comment]
The GitHub labels have been corrected on the labels page (where you make a new label) but they are still inverted color on the issues pages (next to the issue title, in the labels dropdown for filtering, and in the dropdown when assigning a label to an issue)
