### ISSUE TITLE
Couple inverted colors on github

### ISSUE THREAD

**Issue by Californ1a** [liorgrossman/darkness#42]
As per #37 the label colors on the create label page were fixed, however, the labels are still inverted on the issues pages (main issues page, new issue in the dropdown to assign a label, etc.)

The other thing inverted is on commit pages - The highlighting of line additions and deletions shouldn't be inverted (as it is, it shows red for addition and green for removal, the opposite of what it should be).

**Comment by theme1256** [comment]
This should now be fixed, just waiting for Lior to approve the pull request :)

**Comment by liorgrossman** [comment]
Thanks @Californ1a for reporting this, and thanks @theme1256 for pushing a fix :)
Merged to master
