### ISSUE TITLE
Amazon - Profile Picture inverted on home screen (amazon.co.uk)

### ISSUE THREAD

**Issue by Seriell** [liorgrossman/darkness#51]
![](https://i.fl0.co/675_chrome_e393.png)
^ my Avatar is inverted on the home screen of amazon.co.uk

**Comment by theme1256** [comment]
See my comment on #50

**Comment by liorgrossman** [comment]
Yep. This theme does require some work before it's ready.
I suggest that we open issues only for skins that were finished (aka skins with support: 'full' in config.js)
