### ISSUE TITLE
Youtube has a new UI preview enabled for some users

### ISSUE THREAD

**Issue by francislavoie** [liorgrossman/darkness#58]
It seems like Youtube is doing A/B testing of a new UI. Darkness is broken on all themes for it.

Edit: as of july 25th It's turned on everywhere for me now it seems. Still needs fixing.

Edit 2: Well, considering there's a built-in dark mode in youtube now, I guess I don't need darkness for youtube anymore. https://www.youtube.com/new

**Comment by liorgrossman** [comment]
Hi Francis,
I've updated Darkness, so now it builds upon YouTube's new dark theme, while still enabling you to change the color theme to Iceberg, Material, Dusk, etc.

Please pull and compile to get the latest skins:
git checkout master
git pull upstream master
npm install
