### ISSUE TITLE
Flickering on some dark sites

### ISSUE THREAD

**Issue by theme1256** [liorgrossman/darkness#63]
On some sites, where I have Darkness enabled, the background is changing color every other time I click with my mouse.

I don't know if this is a problem with the invert function in CSS in the newest version of chrome, but if that was the case, I guess it would affect all sites.

Right now I've only experienced it on Google Docs, so it might just be Google refreshing the site a lot.

**Comment by theme1256** [comment]
Actually, Github does it too, when scrolling

**Comment by theme1256** [comment]
Actually it just might be a problem on my laptop.
It has previously had issues like that, so I guess I'm of debugging that again...

**Comment by liorgrossman** [comment]
Weird stuff. Hardware acceleration bugs?

**Comment by theme1256** [comment]
Yes, it's Chrome that has problems with my combination of Intel HD Graphics and nVidia Quadro.
