### ISSUE TITLE
icon collides with messages from other plugins

### ISSUE THREAD

**Issue by logicfish** [liorgrossman/darkness#66]
perhaps the icon could be made draggable? it's overriding other buttons at the top-right of webpages etc.

**Comment by logicfish** [comment]
![image](https://user-images.githubusercontent.com/1307024/33242145-21f20d32-d2c8-11e7-9827-4c6169f830dd.png)

**Comment by liorgrossman** [comment]
Yeah, it happens sometimes.
We generally try to position the moon icon in the best location for each website, but every once in a while a tooltip like this pops up, and the moon icon obstructs it.

Making it draggable seems like an option.
Another option is adding an option (inside the dialog) to temporarily hide the icon, until the next pageview.

**Comment by liorgrossman** [comment]
Closing this issue as it's unlikely that we'll make the icon draggable in the foreseeable future.
