### ISSUE TITLE
Submitting New Theme?

### ISSUE THREAD

**Issue by brandy** [liorgrossman/darkness#68]
I just noticed this extension and think it's an awesome idea. 

I'm interested in creating a new theme to match my IDE & Linux theme, are you guys okay with me making pull requests with the theme, or should I just keep it locally?

**Comment by theme1256** [comment]
Sure make a pull request, the worst thing that can happen is that we turn it down or tell you make a couple of changes before we pull :)

**Comment by brandy** [comment]
Awesome, sounds good :)
