### ISSUE TITLE
All-google.scss is not used

### ISSUE THREAD

**Issue by theme1256** [liorgrossman/darkness#70]
Just wanted to let people know that I intend to go through the Google themes and collect the common stuff in the intended "all-google.scss" file, so that when Google updates a class for one of their headers/footers it only has to be updated in one file.

**Comment by liorgrossman** [comment]
Sounds great. Is there a lot of duplicate code between the themes?

**Comment by theme1256** [comment]
Not that much, but somewhere between 50 and 100 lines to handle the google logo, user avatar, user dropdown, appdrawer and notifications.
Besides, it would be prefered that something thats the same when the theme is not on, is still the same when the theme is on 😄

**Comment by liorgrossman** [comment]
Absolutely 😆

**Comment by theme1256** [comment]
Combined in 137c662
