### ISSUE TITLE
Changing the moon icon to be triangular, so it does not obstruct UI elements?

### ISSUE THREAD

**Issue by liorgrossman** [liorgrossman/darkness#79]
I get **many** complaints from users about the moon icon obstructing and covering various UI elements (x buttons, toolbar buttons, etc.)

While many users suggest making it draggable / hide-able, this introduces some **additional complexity** to a very simple product (what if user drags the icon outside the viewport? what is the screen resolution changes? how can a user restore an icon after it's hidden?)

I think the easiest solution might be to change the circular moon icon to a small triangular icon, and put it in the rightmost-topmost corner (top: 0, right: 0) of the screen - for all websites.
That way, it is much less likely that it will cover/obstruct any website's UI buttons.

**What do you think?**
Is there any website where such a triangular icon would not fit well?
Would it interfere with any other extension or functionality?

**Comment by liorgrossman** [comment]
@theme1256 what do you think? Does this solution makes sense, or is there a better way?

**Comment by theme1256** [comment]
I feel like that's one of the good ways to solve it.

We could move the popup in the icon to the popup that appears when clicking the extension icon in the extension part of the toolbar and thus move it completely off the viewport.

I don't know which is better.

**Comment by liorgrossman** [comment]
Yeah, putting it in the toolbar is a good option too.
Pros of putting it in the Chrome toolbar: absolutely 0% chance that it will interfere with the website UI.
Cons of putting it in the Chrome toolbar: some users won't notice they can configure Darkness and toggle the themes, sometimes it requires 2 clicks (if you resize the address bar area, some of the extension icons can be hidden).
Will play with both approaches and see which one works better.

**Comment by liorgrossman** [comment]
I've changed the moon icon across the board to be less obtrusive, and now it's small and positioned in the top-right corner of the window (regardless of the toolbar), and there's no need to move toolbar elements anymore, as far as I could tell.

I hope this will prevent additional toolbar headaches in the future.
Give it a try and let me know what you think.
