### ISSUE TITLE
can't see facebook player controls

### ISSUE THREAD

**Issue by carlospoqw** [liorgrossman/darkness#84]
normal
![image](https://user-images.githubusercontent.com/28213351/44624393-8d72cc00-a8c3-11e8-9a94-8cc91a02c4a8.png)

as you can see whit darkness
![image](https://user-images.githubusercontent.com/28213351/44624389-52709880-a8c3-11e8-8550-d6d231d5afb4.png)

**Comment by theme1256** [comment]
I can't replicate this problem, they are there when I'm hovering over the video and hide when I'm still or not hovering over the video.

**Comment by carlospoqw** [comment]
it was fixed
![image](https://user-images.githubusercontent.com/28213351/46261354-b1c85680-c4c8-11e8-99bf-b6184071e873.png)
