### ISSUE TITLE
Youtube icon

### ISSUE THREAD

**Issue by tasos997** [liorgrossman/darkness#88]
Can you please disable the youtube icon? It' s not even need, cause youtube already has dark mode built in.. And the icon in fullscreen just ruins the experience..

**Comment by liorgrossman** [comment]
Although YouTube has built-in dark theme, some people still prefer to use Darkness' theme (e.g. Iceberg, Matrix, etc.)
The moon icon should not appear in YouTube fullscreen mode, though. That's a bug we need to solve.

**Comment by liorgrossman** [comment]
Merging this issue into https://github.com/liorgrossman/darkness/issues/90
