### ISSUE TITLE
Facebook dark theme bugging in messenger

### ISSUE THREAD

**Issue by DarteX44** [liorgrossman/darkness#89]
**Bug Information**
(visit the affected website → click the moon icon → "Send Feedback" → "Bug Report" → paste here)
* Site: Facebook
* Theme: Iceberg (or any other)
* Browser: Chrome 70.0.3538.102
* Operating System: Windows 10
* Resolution: 1920x1080
* Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

![image](https://user-images.githubusercontent.com/45153463/48679226-ecc43d80-eb8d-11e8-84b7-07bc183e5462.png)

I've noticed that in Facebook messenger on the website, white background started to appear not long ago aroung the messages in the bubbles, doesn't matter what color I choose, and it's kinda irritating that it started to show up only few days ago (also minor fact - when people are showing up online, their "online status circle" is not green, it's purple, I don't mind about this just informing)

**Comment by liorgrossman** [comment]
Can't reproduce this issue, I can't see any white background as shown in the screenshot.
Does it still occur?

**Comment by DarteX44** [comment]
Yes it does, since the moment Facebook revamped the messenger. If you aren't experiencing this issue, I will try removing and adding the addon back

**Comment by DarteX44** [comment]
It's still going, and with the new emoji, it looks ...
![2018-11-29_23-30-52](https://user-images.githubusercontent.com/45153463/49256305-dc824d00-f42e-11e8-8c9c-0e46861e2412.png)
No idea what's happening.

**Comment by Szelethus** [comment]
Hi! I'm experiencing the same issue.

* Site: facebook
* Theme: iceberg
* URL: https://www.facebook.com/
* Darkness Version: 2.0.1 Pro
* Browser: Chrome 70.0.3538.110
* Operating System: Windows 10
* Resolution: 1920x1080
* Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Comment by EgilNextron** [comment]
Same for me, been like that for a couple of months......

* Site: facebook
* Theme: iceberg
* URL: https://www.facebook.com/
* Darkness Version: 2.0.5 Pro
* Browser: Chrome 71.0.3578.98
* Operating System: Windows 10
* Resolution: 1920x1080
* Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by halflings** [comment]
Also started experiencing the same issue today; this seems to be some new version of Messenger that is gradually being rolled out?

**Comment by DarteX44** [comment]
Also the fact that it automatically turns chat in messenger to orange color, which is kinda "unusual" and my eyes aren't used to it is kind of a shit feature...

**Comment by Szelethus** [comment]
Very much appreciated!

**Comment by liorgrossman** [comment]
Same here, just got the new chat windows.
Thanks for the fix @theme1256!
