### ISSUE TITLE
YOUTUBE ICON BUG

### ISSUE THREAD

**Issue by YaraviMegpoid** [liorgrossman/darkness#90]
* Site: youtube
* Theme: base16tomorrow
* URL: https://www.youtube.com/watch?v=gIud0gJ3pKw&t=4s
* Darkness Version: 2.0.0 Unknown
* Browser: Chrome 70.0.3538.102
* Operating System: Windows 10
* Resolution: 1920x1080
* Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

**Bug Description**

Hello, there is an annoying error, the logo of the extension is always in the upper right corner in full screen, could you solve it please?
I am a pro user, I already paid.
Regards!

**Screenshots**
![bug](https://user-images.githubusercontent.com/45158054/48685968-f1cdc080-eb7e-11e8-8512-97d9f98efa68.png)

**Comment by liorgrossman** [comment]
Can confirm. This is probably a new bug.

**Comment by liorgrossman** [comment]
Fixed this bug in https://github.com/liorgrossman/darkness/commit/f7617b9cc07fb214d425371ec9287223c5cc3025
Will also deploy a new version to Chrome Web Store today

**Comment by swilson98** [comment]
This has come back. Please fix, or add option to remove the corner icon completely.

**Comment by tasoschan** [comment]
It came back yes. please try to fix it

**Comment by liorgrossman** [comment]
Thanks @theme1256 , packing and deploying a new version of Darkness now.
Please expect an update within 24hr.
