### ISSUE TITLE
Facebook Theme - Too dark to read names when hovering over reacts

### ISSUE THREAD

**Issue by Ghost942** [liorgrossman/darkness#91]
**Is your feature request related to a problem you've encountered? Please describe.**
Current Facebook themes have text that is too dark to read concerning reacts on posts.

**Describe the solution you'd like to see**
Perhaps a light color could be used to read text. Current colors are a strain to read.

**Comment by theme1256** [comment]
What theme are you using?

**Comment by Ghost942** [comment]
Current Theme is "Tomorrow"

**Comment by theme1256** [comment]
Just to be clear, it's this popup box that has the problem, right?

![image](https://user-images.githubusercontent.com/9347753/49065737-2bf22e80-f21f-11e8-9531-38095765a004.png)

**Comment by Ghost942** [comment]
Yes, but it is when there are names. The names are very hard to read when mousing over said popup box.

**Comment by CypherDragon** [comment]
+1 for this issue - and it applies to any theme. I'm a Darkness Pro user, and can verify the CSS for the Facebook theme is almost impossible to read when hovering.
Screenshot (names blurred for privacy):
![image](https://user-images.githubusercontent.com/45954806/50125871-3c9b3080-0230-11e9-8f43-7dadea43209e.png)

Sys info:
* Site: facebook
* Theme: iceberg
* URL: https://www.facebook.com/
* Darkness Version: 2.0.4 Pro
* Browser: Chrome 71.0.3578.98
* Operating System: Windows 10
* Resolution: 2560x1080
* Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
