### ISSUE TITLE
Google Drive Support

### ISSUE THREAD

**Issue by XSmil3y** [liorgrossman/darkness#96]
I'd like to see the dark theme working on Google Drive. It seems to be a part of almost every other Google app, even those I've never used/heard of! 
Drive is an app I use constantly, and sometimes the white screen is really taxing on my eyes. I'm enjoying the themes on the other sites I use, and it feels well worth the money. I just feel like I need this last site to work now!

**Comment by theme1256** [comment]
Drive and Docs are already supported, it's just because I forgot to mark Drive as "full" support.

**Comment by liorgrossman** [comment]
Will deploy a version with your fix to Chrome & Firefox stores as well
https://github.com/liorgrossman/darkness/commit/945293d5f6e97b25c75260113d2176188b09300d
