### ISSUE TITLE
Google color picker inverted

### ISSUE THREAD

**Issue by iSnackyCracky** [liorgrossman/darkness#97]
**Bug Information**
* Site: google
* Theme: material
* URL: https://www.google.com/search?num=20&newwindow=1&source=hp&ei=RbsGXK_cD4WhsgH005WQAg&q=color+picker&btnK=Google-Suche&oq=color+picker&gs_l=psy-ab.3..35i39j0l3j0i203j0l5.1192.2849..3023...0.0..0.186.1158.11j2......0....1..gws-wiz.....0..0i131j0i20i263.kbvwU6Xnhs0
* Darkness Version: 2.0.1 Pro
* Browser: Chrome 70.0.3538.110
* Operating System: Windows 10
* Resolution: 1920x1080
* Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

**Bug Description**
The Google color-picker has some elements with inverted colors.
This affects all themes.

**Screenshots**
![image](https://user-images.githubusercontent.com/20481463/49461601-55e5bb00-f7f4-11e8-9f54-98cc7bab7770.png)

**Comment by TheGooner93** [comment]
Google doesnt provide the color picker in the link mentioned above by @iSnackyCracky ; how else can this be reproduced?

**Comment by theme1256** [comment]
@TheGooner93 You just google ["Color picker"](https://www.google.com/search?q=color+picker) to summon it.
I've just pushed changes to fix it on my machine.
