### ISSUE TITLE
Update required in the Readme.md

### ISSUE THREAD

**Issue by TheGooner93** [liorgrossman/darkness#99]
**Is your feature request related to a problem you've encountered? Please describe.**
https://github.com/liorgrossman/darkness/blob/master/README.md does not contained updated button texts, under the section Installation->Loading it in Chrome:->Point 4

**Describe the solution you'd like to see**
I have created a PR for the fix, just an update to the readme : https://github.com/liorgrossman/darkness/pull/98

**Comment by liorgrossman** [comment]
Thanks for the contribution @TheGooner93 
Merged the PR into master
